---
# Inventario prueba técnica — equipos Cisco
all:
  children:
    cisco:
      hosts:
        RTR-Prod-Gateway1:
          ansible_host: 10.0.0.80
        SW-Prod-Core1:
          ansible_host: 10.0.0.81
        SW-Prod-Edge1:
          ansible_host: 10.0.0.82
