---
- name: Restaurar escenario de laboratorio
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Revertir cambio en equipo
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: "interface {{ fail_interface }}"
      when: inventory_hostname == fail_host
      no_log: true
